/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PORTMAP_H_RPCGEN
#define _PORTMAP_H_RPCGEN




#ifdef __cplusplus
extern "C" {
#endif

#define PMAP_PORT 111

struct pmap_mapping {
	u_int prog;
	u_int vers;
	u_int prot;
	u_int port;
};
typedef struct pmap_mapping pmap_mapping;

struct pmap_call_args {
	u_int prog;
	u_int vers;
	u_int proc;
	struct {
		u_int args_len;
		char *args_val;
	} args;
};
typedef struct pmap_call_args pmap_call_args;

struct pmap_call_result {
	u_int port;
	struct {
		u_int res_len;
		char *res_val;
	} res;
};
typedef struct pmap_call_result pmap_call_result;

struct pmap_mapping_list {
	pmap_mapping map;
	struct pmap_mapping_list *next;
};
typedef struct pmap_mapping_list pmap_mapping_list;

struct pmap_dump_result {
	struct pmap_mapping_list *list;
};
typedef struct pmap_dump_result pmap_dump_result;

#define PMAP_PROGRAM 100000
#define PMAP_V2 2

#if defined(__STDC__) || defined(__cplusplus)
#define PMAP_NULL 0
extern  void * pmap_null_2(void *, CLIENT *);
extern  void * pmap_null_2_svc(void *, struct svc_req *);
#define PMAP_SET 1
extern  bool_t * pmap_set_2(pmap_mapping *, CLIENT *);
extern  bool_t * pmap_set_2_svc(pmap_mapping *, struct svc_req *);
#define PMAP_UNSET 2
extern  bool_t * pmap_unset_2(pmap_mapping *, CLIENT *);
extern  bool_t * pmap_unset_2_svc(pmap_mapping *, struct svc_req *);
#define PMAP_GETPORT 3
extern  u_int * pmap_getport_2(pmap_mapping *, CLIENT *);
extern  u_int * pmap_getport_2_svc(pmap_mapping *, struct svc_req *);
#define PMAP_DUMP 4
extern  pmap_mapping_list * pmap_dump_2(void *, CLIENT *);
extern  pmap_mapping_list * pmap_dump_2_svc(void *, struct svc_req *);
#define PMAP_CALLIT 5
extern  pmap_call_result * pmap_callit_2(pmap_call_args *, CLIENT *);
extern  pmap_call_result * pmap_callit_2_svc(pmap_call_args *, struct svc_req *);
extern int pmap_program_2_freeresult (SVCXPRT *, zdrproc_t, caddr_t);

#else /* K&R C */
#define PMAP_NULL 0
extern  void * pmap_null_2();
extern  void * pmap_null_2_svc();
#define PMAP_SET 1
extern  bool_t * pmap_set_2();
extern  bool_t * pmap_set_2_svc();
#define PMAP_UNSET 2
extern  bool_t * pmap_unset_2();
extern  bool_t * pmap_unset_2_svc();
#define PMAP_GETPORT 3
extern  u_int * pmap_getport_2();
extern  u_int * pmap_getport_2_svc();
#define PMAP_DUMP 4
extern  pmap_mapping_list * pmap_dump_2();
extern  pmap_mapping_list * pmap_dump_2_svc();
#define PMAP_CALLIT 5
extern  pmap_call_result * pmap_callit_2();
extern  pmap_call_result * pmap_callit_2_svc();
extern int pmap_program_2_freeresult ();
#endif /* K&R C */

/* the zdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t zdr_pmap_mapping (ZDR *, pmap_mapping*);
extern  bool_t zdr_pmap_call_args (ZDR *, pmap_call_args*);
extern  bool_t zdr_pmap_call_result (ZDR *, pmap_call_result*);
extern  bool_t zdr_pmap_mapping_list (ZDR *, pmap_mapping_list*);
extern  bool_t zdr_pmap_dump_result (ZDR *, pmap_dump_result*);

#else /* K&R C */
extern bool_t zdr_pmap_mapping ();
extern bool_t zdr_pmap_call_args ();
extern bool_t zdr_pmap_call_result ();
extern bool_t zdr_pmap_mapping_list ();
extern bool_t zdr_pmap_dump_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PORTMAP_H_RPCGEN */
