/* -*-  mode:c; tab-width:8; c-basic-offset:8; indent-tabs-mode:nil;  -*- */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCBIND_DATA_H_RPCGEN
#define _RPCBIND_DATA_H_RPCGEN

#include <nfsc/libnfs-zdr.h>


#ifdef __cplusplus
extern "C" {
#endif


struct mapping {
	struct mapping *next;
	uint32_t port;
	uint32_t prog;
	uint32_t vers;
	char *netid;
	char *addr;
	char *owner;
};
typedef struct mapping mapping;

typedef mapping *mapping_ptr;

/* the zdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  uint32_t zdr_mapping (ZDR *, mapping*);
extern  uint32_t zdr_mapping_ptr (ZDR *, mapping_ptr*);

#else /* K&R C */
extern uint32_t zdr_mapping ();
extern uint32_t zdr_mapping_ptr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCBIND_DATA_H_RPCGEN */
