/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NSM_H_RPCGEN
#define _NSM_H_RPCGEN




#ifdef __cplusplus
extern "C" {
#endif

#define NSM_MAXSTRLEN 1024

struct nsm_name {
	char *mon_name;
};
typedef struct nsm_name nsm_name;

enum nsmstat1 {
	NSM_STAT_SUCC = 0,
	NSM_STAT_FAIL = 1,
};
typedef enum nsmstat1 nsmstat1;

struct nsm_stat_res {
	nsmstat1 res;
	int state;
};
typedef struct nsm_stat_res nsm_stat_res;

struct nsm_stat {
	int state;
};
typedef struct nsm_stat nsm_stat;

struct nsm_my_id {
	char *my_name;
	int my_prog;
	int my_vers;
	int my_proc;
};
typedef struct nsm_my_id nsm_my_id;

struct nsm_mon_id {
	char *mon_name;
	struct nsm_my_id my_id;
};
typedef struct nsm_mon_id nsm_mon_id;

struct nsm_mon {
	struct nsm_mon_id mon_id;
	char priv[16];
};
typedef struct nsm_mon nsm_mon;

struct nsm_stat_chg {
	char *mon_name;
	int state;
};
typedef struct nsm_stat_chg nsm_stat_chg;

#define NSM_PROGRAM 100024
#define NSM_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define NSM1_NULL 0
extern  void * nsm1_null_1(void *, CLIENT *);
extern  void * nsm1_null_1_svc(void *, struct svc_req *);
#define NSM1_STAT 1
extern  struct nsm_stat_res * nsm1_stat_1(struct nsm_name *, CLIENT *);
extern  struct nsm_stat_res * nsm1_stat_1_svc(struct nsm_name *, struct svc_req *);
#define NSM1_MON 2
extern  struct nsm_stat_res * nsm1_mon_1(struct nsm_mon *, CLIENT *);
extern  struct nsm_stat_res * nsm1_mon_1_svc(struct nsm_mon *, struct svc_req *);
#define NSM1_UNMON 3
extern  struct nsm_stat * nsm1_unmon_1(struct nsm_mon_id *, CLIENT *);
extern  struct nsm_stat * nsm1_unmon_1_svc(struct nsm_mon_id *, struct svc_req *);
#define NSM1_UNMON_ALL 4
extern  struct nsm_stat * nsm1_unmon_all_1(struct nsm_my_id *, CLIENT *);
extern  struct nsm_stat * nsm1_unmon_all_1_svc(struct nsm_my_id *, struct svc_req *);
#define NSM1_SIMU_CRASH 5
extern  void * nsm1_simu_crash_1(void *, CLIENT *);
extern  void * nsm1_simu_crash_1_svc(void *, struct svc_req *);
#define NSM1_NOTIFY 6
extern  void * nsm1_notify_1(struct nsm_stat_chg *, CLIENT *);
extern  void * nsm1_notify_1_svc(struct nsm_stat_chg *, struct svc_req *);
extern int nsm_program_1_freeresult (SVCXPRT *, zdrproc_t, caddr_t);

#else /* K&R C */
#define NSM1_NULL 0
extern  void * nsm1_null_1();
extern  void * nsm1_null_1_svc();
#define NSM1_STAT 1
extern  struct nsm_stat_res * nsm1_stat_1();
extern  struct nsm_stat_res * nsm1_stat_1_svc();
#define NSM1_MON 2
extern  struct nsm_stat_res * nsm1_mon_1();
extern  struct nsm_stat_res * nsm1_mon_1_svc();
#define NSM1_UNMON 3
extern  struct nsm_stat * nsm1_unmon_1();
extern  struct nsm_stat * nsm1_unmon_1_svc();
#define NSM1_UNMON_ALL 4
extern  struct nsm_stat * nsm1_unmon_all_1();
extern  struct nsm_stat * nsm1_unmon_all_1_svc();
#define NSM1_SIMU_CRASH 5
extern  void * nsm1_simu_crash_1();
extern  void * nsm1_simu_crash_1_svc();
#define NSM1_NOTIFY 6
extern  void * nsm1_notify_1();
extern  void * nsm1_notify_1_svc();
extern int nsm_program_1_freeresult ();
#endif /* K&R C */

/* the zdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t zdr_nsm_name (ZDR *, nsm_name*);
extern  bool_t zdr_nsmstat1 (ZDR *, nsmstat1*);
extern  bool_t zdr_nsm_stat_res (ZDR *, nsm_stat_res*);
extern  bool_t zdr_nsm_stat (ZDR *, nsm_stat*);
extern  bool_t zdr_nsm_my_id (ZDR *, nsm_my_id*);
extern  bool_t zdr_nsm_mon_id (ZDR *, nsm_mon_id*);
extern  bool_t zdr_nsm_mon (ZDR *, nsm_mon*);
extern  bool_t zdr_nsm_stat_chg (ZDR *, nsm_stat_chg*);

#else /* K&R C */
extern bool_t zdr_nsm_name ();
extern bool_t zdr_nsmstat1 ();
extern bool_t zdr_nsm_stat_res ();
extern bool_t zdr_nsm_stat ();
extern bool_t zdr_nsm_my_id ();
extern bool_t zdr_nsm_mon_id ();
extern bool_t zdr_nsm_mon ();
extern bool_t zdr_nsm_stat_chg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NSM_H_RPCGEN */
